import type { MetaData } from 'next'
import React from 'react'

const metaData: MetaData = {
    title: 'About Project Harmony',
    description: 'Generated by create next app',
}
const About = () => {
  return (
    <div>
      <h1 className='text-[4rem]'>About</h1>
    </div>
  )
}

export default About
